pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "portfolio-app"
        DOCKER_CONTAINER = "portfolio-container"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/omwarkri/portfolio-amplify.git'
            }
        }

        // ✅ Add this stage for Docker build & run
        stage('Docker Build & Run') {
            steps {
                sh '''
                    docker build -t $DOCKER_IMAGE .
                    docker stop $DOCKER_CONTAINER || true
                    docker rm $DOCKER_CONTAINER || true
                    docker run -d -p 3000:3000 --name $DOCKER_CONTAINER $DOCKER_IMAGE
                '''
            }
        }
    }

    post {
        success {
            echo "✅ Deployment successful! Open: http://<192.168.153.131>:3000"
        }
        failure {
            echo "❌ Deployment failed. Check logs in Jenkins console."
        }
    }
}
