pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/omwarkri/portfolio-amplify.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Build') {
            steps {
                sh 'npm run build'
            }
        }

        stage('Test') {
            steps {
                sh 'npm test || echo "No tests"'
            }
        }
        stage('Deploy') {
    steps {
        sh '''
            nohup npm run start -- -p 3000 -H 0.0.0.0 > nextjs.log 2>&1 &
        '''
        echo "Next.js app is running at http://192.168.153.131:3000"
    }
}


    }
}
